### ISSUE TITLE
Python 3.6 Fails to Install

### ISSUE THREAD

**Issue by Nythepegasus** [autopilot-rs/autopy#1]
```
Collecting autopy
  Using cached https://files.pythonhosted.org/packages/93/d7/209f9faed7eddfeec03f2353f9d53ea93ba6cb1c92e657467d4fa6e45dba/autopy-0.51.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/8g/2qzj44fn7b906lldvmcy0dfm0000gn/T/pip-install-dkdc0hji/autopy/setup.py", line 50
        print 'Updating __init__.py'
                                   ^
    SyntaxError: Missing parentheses in call to 'print'. Did you mean print(print 'Updating __init__.py')?
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/8g/2qzj44fn7b906lldvmcy0dfm0000gn/T/pip-install-dkdc0hji/autopy/

```
When trying to install from pip (Version 10.0.1) I get the errors above. I'm also running from MacOS Sierra 10.12.6.

**Comment by Nythepegasus** [comment]
It seems I can only get it to install on python 2.7 from source. Pip on both versions doesn't seem to work. I don't know if it's just me, or if others have this issue too.

**Comment by msanders** [comment]
Sorry about that @Nythepegasus. This is from the previous (legacy) version of AutoPy. I'm still in the process of uploading this fork to PyPI. Will remove these instructions from the README for now to reduce confusion.

**Comment by msanders** [comment]
OK, this should be fixed now. I've uploaded the new version along with binary wheel distributions.
