### ISSUE TITLE
Seeming no way to execute modifiers with mouse click

### ISSUE THREAD

**Issue by tomprodehl** [autopilot-rs/autopy#14]
Need to send CTRL-CLICK or SHIFT-CLICK or any modifiers with mouse click. API shows no support.

**Comment by msanders** [comment]
This can be accomplished using the following:

```python
autopy.key.toggle(autopy.key.Code.CONTROL, True)
autopy.mouse.click()
autopy.key.toggle(autopy.key.Code.CONTROL, False)
```

I think it's best to separate these two things so will be closing out this issue for now.
