### ISSUE TITLE
Some keys missing in official documentation

### ISSUE THREAD

**Issue by pevogam** [autopilot-rs/autopy#2]
HI, I was just checking the new key names at

https://www.autopy.org/documentation/api-reference/key.html

and CAPS_LOCK and more importantly SHIFT are missing from the regular keys (`Code`) while (thankfully) they are still present in the source. Maybe it's better if you could update them in the documentation as well because people would wonder why is SHIFT no longer supported as a nonmodifier key. Thanks!

**Comment by msanders** [comment]
Good catch @pevogam! Thanks for reporting.
