### ISSUE TITLE
Cannot install autopy on ArchLinux | "could not compile spin"

### ISSUE THREAD

**Issue by ornariece** [autopilot-rs/autopy#20]
Hi, I followed the instructions on how to install the package on Arch Linux, with Python 3.7, and i get this error when trying to install autopy with pip : 

>  [amram@archlinux ~]$ pip install -U autopy
Collecting autopy
  Using cached https://files.pythonhosted.org/packages/cb/99/9203ea5442f3bd52695fce191305eeb6de63ff29a9a05d0c5ecb60ec4a69/autopy-1.0.1.tar.gz
Installing collected packages: autopy
  Running setup.py install for autopy ... error
    Complete output from command /usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-xv02w1v3/autopy/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-3ofcoj9a/install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_py
    creating build
    creating build/lib.linux-x86_64-3.7
    creating build/lib.linux-x86_64-3.7/autopy
    copying autopy/__init__.py -> build/lib.linux-x86_64-3.7/autopy
    running build_ext
    running build_rust
    cargo rustc --lib --manifest-path Cargo.toml --features pyo3/extension-module pyo3/python3 --release --verbose -- --crate-type cdylib
       Compiling cfg-if v0.1.2
       Compiling nodrop v0.1.12
       Compiling lazy_static v1.0.0
       Compiling scopeguard v0.3.3
         Running `rustc --crate-name cfg_if /home/amram/.cargo/registry/src/github.com-1ecc6299db9ec823/cfg-if-0.1.2/src/lib.rs --crate-type lib --emit=dep-info,link -C opt-level=3 -C metadata=528ea4126aa4c125 -C extra-filename=-528ea4126aa4c125 --out-dir /tmp/pip-install-xv02w1v3/autopy/target/release/deps -L dependency=/tmp/pip-install-xv02w1v3/autopy/target/release/deps --cap-lints allow`
         Running `rustc --crate-name nodrop /home/amram/.cargo/registry/src/github.com-1ecc6299db9ec823/nodrop-0.1.12/src/lib.rs --crate-type lib --emit=dep-info,link -C opt-level=3 -C metadata=f2d3128ffe44f111 -C extra-filename=-f2d3128ffe44f111 --out-dir /tmp/pip-install-xv02w1v3/autopy/target/release/deps -L dependency=/tmp/pip-install-xv02w1v3/autopy/target/release/deps --cap-lints allow`
         Running `rustc --crate-name lazy_static /home/amram/.cargo/registry/src/github.com-1ecc6299db9ec823/lazy_static-1.0.0/src/lib.rs --crate-type lib --emit=dep-info,link -C opt-level=3 -C metadata=eecf5994cf47fed5 -C extra-filename=-eecf5994cf47fed5 --out-dir /tmp/pip-install-xv02w1v3/autopy/target/release/deps -L dependency=/tmp/pip-install-xv02w1v3/autopy/target/release/deps --cap-lints allow`
         Running `rustc --crate-name scopeguard /home/amram/.cargo/registry/src/github.com-1ecc6299db9ec823/scopeguard-0.3.3/src/lib.rs --crate-type lib --emit=dep-info,link -C opt-level=3 --cfg 'feature="default"' --cfg 'feature="use_std"' -C metadata=98baa8fd972f2eeb -C extra-filename=-98baa8fd972f2eeb --out-dir /tmp/pip-install-xv02w1v3/autopy/target/release/deps -L dependency=/tmp/pip-install-xv02w1v3/autopy/target/release/deps --cap-lints allow`
       Compiling memoffset v0.2.1
         Running `rustc --crate-name memoffset /home/amram/.cargo/registry/src/github.com-1ecc6299db9ec823/memoffset-0.2.1/src/lib.rs --crate-type lib --emit=dep-info,link -C opt-level=3 -C metadata=a1404034f8c99834 -C extra-filename=-a1404034f8c99834 --out-dir /tmp/pip-install-xv02w1v3/autopy/target/release/deps -L dependency=/tmp/pip-install-xv02w1v3/autopy/target/release/deps --cap-lints allow`
       Compiling rayon-core v1.4.0
         Running `rustc --crate-name build_script_build /home/amram/.cargo/registry/src/github.com-1ecc6299db9ec823/rayon-core-1.4.0/build.rs --crate-type bin --emit=dep-info,link -C opt-level=3 -C metadata=d412ea84f46cc258 -C extra-filename=-d412ea84f46cc258 --out-dir /tmp/pip-install-xv02w1v3/autopy/target/release/build/rayon-core-d412ea84f46cc258 -L dependency=/tmp/pip-install-xv02w1v3/autopy/target/release/deps --cap-lints allow`
       Compiling void v1.0.2
         Running `rustc --crate-name void /home/amram/.cargo/registry/src/github.com-1ecc6299db9ec823/void-1.0.2/src/lib.rs --crate-type lib --emit=dep-info,link -C opt-level=3 -C metadata=6e510b2ad234ff9a -C extra-filename=-6e510b2ad234ff9a --out-dir /tmp/pip-install-xv02w1v3/autopy/target/release/deps -L dependency=/tmp/pip-install-xv02w1v3/autopy/target/release/deps --cap-lints allow`
       Compiling unicode-xid v0.1.0
         Running `rustc --crate-name unicode_xid /home/amram/.cargo/registry/src/github.com-1ecc6299db9ec823/unicode-xid-0.1.0/src/lib.rs --crate-type lib --emit=dep-info,link -C opt-level=3 --cfg 'feature="default"' -C metadata=c51128dd11b51929 -C extra-filename=-c51128dd11b51929 --out-dir /tmp/pip-install-xv02w1v3/autopy/target/release/deps -L dependency=/tmp/pip-install-xv02w1v3/autopy/target/release/deps --cap-lints allow`
       Compiling libc v0.2.40
         Running `rustc --crate-name libc /home/amram/.cargo/registry/src/github.com-1ecc6299db9ec823/libc-0.2.40/src/lib.rs --crate-type lib --emit=dep-info,link -C opt-level=3 --cfg 'feature="default"' --cfg 'feature="use_std"' -C metadata=49c3f0ab615e4743 -C extra-filename=-49c3f0ab615e4743 --out-dir /tmp/pip-install-xv02w1v3/autopy/target/release/deps -L dependency=/tmp/pip-install-xv02w1v3/autopy/target/release/deps --cap-lints allow`
       Compiling ucd-util v0.1.1
         Running `rustc --crate-name ucd_util /home/amram/.cargo/registry/src/github.com-1ecc6299db9ec823/ucd-util-0.1.1/src/lib.rs --crate-type lib --emit=dep-info,link -C opt-level=3 -C metadata=b5f6de7dd1617814 -C extra-filename=-b5f6de7dd1617814 --out-dir /tmp/pip-install-xv02w1v3/autopy/target/release/deps -L dependency=/tmp/pip-install-xv02w1v3/autopy/target/release/deps --cap-lints allow`
       Compiling regex v0.2.10
         Running `rustc --crate-name build_script_build /home/amram/.cargo/registry/src/github.com-1ecc6299db9ec823/regex-0.2.10/build.rs --crate-type bin --emit=dep-info,link -C opt-level=3 --cfg 'feature="default"' -C metadata=d7d853e87cb70d14 -C extra-filename=-d7d853e87cb70d14 --out-dir /tmp/pip-install-xv02w1v3/autopy/target/release/build/regex-d7d853e87cb70d14 -L dependency=/tmp/pip-install-xv02w1v3/autopy/target/release/deps --cap-lints allow`
       Compiling num-traits v0.2.2
         Running `rustc --crate-name num_traits /home/amram/.cargo/registry/src/github.com-1ecc6299db9ec823/num-traits-0.2.2/src/lib.rs --crate-type lib --emit=dep-info,link -C opt-level=3 --cfg 'feature="default"' --cfg 'feature="std"' -C metadata=a59c842e44ca6fba -C extra-filename=-a59c842e44ca6fba --out-dir /tmp/pip-install-xv02w1v3/autopy/target/release/deps -L dependency=/tmp/pip-install-xv02w1v3/autopy/target/release/deps --cap-lints allow`
       Compiling pkg-config v0.3.11
         Running `rustc --crate-name pkg_config /home/amram/.cargo/registry/src/github.com-1ecc6299db9ec823/pkg-config-0.3.11/src/lib.rs --crate-type lib --emit=dep-info,link -C opt-level=3 -C metadata=99765f6df377c2dd -C extra-filename=-99765f6df377c2dd --out-dir /tmp/pip-install-xv02w1v3/autopy/target/release/deps -L dependency=/tmp/pip-install-xv02w1v3/autopy/target/release/deps --cap-lints allow`
       Compiling byteorder v1.2.2
         Running `rustc --crate-name byteorder /home/amram/.cargo/registry/src/github.com-1ecc6299db9ec823/byteorder-1.2.2/src/lib.rs --crate-type lib --emit=dep-info,link -C opt-level=3 --cfg 'feature="default"' --cfg 'feature="std"' -C metadata=edd1723e36273c0a -C extra-filename=-edd1723e36273c0a --out-dir /tmp/pip-install-xv02w1v3/autopy/target/release/deps -L dependency=/tmp/pip-install-xv02w1v3/autopy/target/release/deps --cap-lints allow`
       Compiling adler32 v1.0.2
         Running `rustc --crate-name adler32 /home/amram/.cargo/registry/src/github.com-1ecc6299db9ec823/adler32-1.0.2/src/lib.rs --crate-type lib --emit=dep-info,link -C opt-level=3 -C metadata=9fe7d7fbfcf98658 -C extra-filename=-9fe7d7fbfcf98658 --out-dir /tmp/pip-install-xv02w1v3/autopy/target/release/deps -L dependency=/tmp/pip-install-xv02w1v3/autopy/target/release/deps --cap-lints allow`
       Compiling either v1.5.0
         Running `rustc --crate-name either /home/amram/.cargo/registry/src/github.com-1ecc6299db9ec823/either-1.5.0/src/lib.rs --crate-type lib --emit=dep-info,link -C opt-level=3 --cfg 'feature="default"' --cfg 'feature="use_std"' -C metadata=f2573cb040b9e2f8 -C extra-filename=-f2573cb040b9e2f8 --out-dir /tmp/pip-install-xv02w1v3/autopy/target/release/deps -L dependency=/tmp/pip-install-xv02w1v3/autopy/target/release/deps --cap-lints allow`
       Compiling unicode-xid v0.0.4
         Running `rustc --crate-name unicode_xid /home/amram/.cargo/registry/src/github.com-1ecc6299db9ec823/unicode-xid-0.0.4/src/lib.rs --crate-type lib --emit=dep-info,link -C opt-level=3 --cfg 'feature="default"' -C metadata=cc1c9c4eafb6af20 -C extra-filename=-cc1c9c4eafb6af20 --out-dir /tmp/pip-install-xv02w1v3/autopy/target/release/deps -L dependency=/tmp/pip-install-xv02w1v3/autopy/target/release/deps --cap-lints allow`
       Compiling utf8-ranges v1.0.0
         Running `rustc --crate-name utf8_ranges /home/amram/.cargo/registry/src/github.com-1ecc6299db9ec823/utf8-ranges-1.0.0/src/lib.rs --crate-type lib --emit=dep-info,link -C opt-level=3 -C metadata=1612a6a54fe592a9 -C extra-filename=-1612a6a54fe592a9 --out-dir /tmp/pip-install-xv02w1v3/autopy/target/release/deps -L dependency=/tmp/pip-install-xv02w1v3/autopy/target/release/deps --cap-lints allow`
       Compiling version_check v0.1.3
         Running `rustc --crate-name version_check /home/amram/.cargo/registry/src/github.com-1ecc6299db9ec823/version_check-0.1.3/src/lib.rs --crate-type lib --emit=dep-info,link -C opt-level=3 -C metadata=b0384d759e3b30ec -C extra-filename=-b0384d759e3b30ec --out-dir /tmp/pip-install-xv02w1v3/autopy/target/release/deps -L dependency=/tmp/pip-install-xv02w1v3/autopy/target/release/deps --cap-lints allow`
       Compiling color_quant v1.0.0
         Running `rustc --crate-name color_quant /home/amram/.cargo/registry/src/github.com-1ecc6299db9ec823/color_quant-1.0.0/src/lib.rs --crate-type lib --emit=dep-info,link -C opt-level=3 -C metadata=582dc3b21c01cdef -C extra-filename=-582dc3b21c01cdef --out-dir /tmp/pip-install-xv02w1v3/autopy/target/release/deps -L dependency=/tmp/pip-install-xv02w1v3/autopy/target/release/deps --cap-lints allow`
       Compiling bitflags v1.0.2
         Running `rustc --crate-name bitflags /home/amram/.cargo/registry/src/github.com-1ecc6299db9ec823/bitflags-1.0.2/src/lib.rs --crate-type lib --emit=dep-info,link -C opt-level=3 --cfg 'feature="default"' -C metadata=1f757bfc17d72aac -C extra-filename=-1f757bfc17d72aac --out-dir /tmp/pip-install-xv02w1v3/autopy/target/release/deps -L dependency=/tmp/pip-install-xv02w1v3/autopy/target/release/deps --cap-lints allow`
       Compiling quote v0.3.15
         Running `rustc --crate-name quote /home/amram/.cargo/registry/src/github.com-1ecc6299db9ec823/quote-0.3.15/src/lib.rs --crate-type lib --emit=dep-info,link -C opt-level=3 -C metadata=023da69ae82ccd33 -C extra-filename=-023da69ae82ccd33 --out-dir /tmp/pip-install-xv02w1v3/autopy/target/release/deps -L dependency=/tmp/pip-install-xv02w1v3/autopy/target/release/deps --cap-lints allow`
       Compiling lzw v0.10.0
         Running `rustc --crate-name lzw /home/amram/.cargo/registry/src/github.com-1ecc6299db9ec823/lzw-0.10.0/src/lib.rs --crate-type lib --emit=dep-info,link -C opt-level=3 --cfg 'feature="default"' --cfg 'feature="raii_no_panic"' -C metadata=f6340d5583a497f3 -C extra-filename=-f6340d5583a497f3 --out-dir /tmp/pip-install-xv02w1v3/autopy/target/release/deps -L dependency=/tmp/pip-install-xv02w1v3/autopy/target/release/deps --cap-lints allow`
       Compiling scoped_threadpool v0.1.9
         Running `rustc --crate-name scoped_threadpool /home/amram/.cargo/registry/src/github.com-1ecc6299db9ec823/scoped_threadpool-0.1.9/src/lib.rs --crate-type lib --emit=dep-info,link -C opt-level=3 -C metadata=5d82f6e2ad0b5e9f -C extra-filename=-5d82f6e2ad0b5e9f --out-dir /tmp/pip-install-xv02w1v3/autopy/target/release/deps -L dependency=/tmp/pip-install-xv02w1v3/autopy/target/release/deps --cap-lints allow`
       Compiling spin v0.4.8
         Running `rustc --crate-name spin /home/amram/.cargo/registry/src/github.com-1ecc6299db9ec823/spin-0.4.8/src/lib.rs --crate-type lib --emit=dep-info,link -C opt-level=3 --cfg 'feature="asm"' --cfg 'feature="const_fn"' --cfg 'feature="core_intrinsics"' --cfg 'feature="default"' --cfg 'feature="once"' --cfg 'feature="unstable"' -C metadata=6da928f3fd28acf3 -C extra-filename=-6da928f3fd28acf3 --out-dir /tmp/pip-install-xv02w1v3/autopy/target/release/deps -L dependency=/tmp/pip-install-xv02w1v3/autopy/target/release/deps --cap-lints allow`
       Compiling crossbeam-utils v0.2.2
         Running `rustc --crate-name crossbeam_utils /home/amram/.cargo/registry/src/github.com-1ecc6299db9ec823/crossbeam-utils-0.2.2/src/lib.rs --crate-type lib --emit=dep-info,link -C opt-level=3 --cfg 'feature="default"' --cfg 'feature="use_std"' -C metadata=87effb4408bcc1a4 -C extra-filename=-87effb4408bcc1a4 --out-dir /tmp/pip-install-xv02w1v3/autopy/target/release/deps -L dependency=/tmp/pip-install-xv02w1v3/autopy/target/release/deps --extern cfg_if=/tmp/pip-install-xv02w1v3/autopy/target/release/deps/libcfg_if-528ea4126aa4c125.rlib --cap-lints allow`
       Compiling log v0.4.1
         Running `rustc --crate-name log /home/amram/.cargo/registry/src/github.com-1ecc6299db9ec823/log-0.4.1/src/lib.rs --crate-type lib --emit=dep-info,link -C opt-level=3 --cfg 'feature="std"' -C metadata=875bcf99f6451ab8 -C extra-filename=-875bcf99f6451ab8 --out-dir /tmp/pip-install-xv02w1v3/autopy/target/release/deps -L dependency=/tmp/pip-install-xv02w1v3/autopy/target/release/deps --extern cfg_if=/tmp/pip-install-xv02w1v3/autopy/target/release/deps/libcfg_if-528ea4126aa4c125.rlib --cap-lints allow`
    error[E0635]: unknown feature `const_atomic_usize_new`
     --> /home/amram/.cargo/registry/src/github.com-1ecc6299db9ec823/spin-0.4.8/src/lib.rs:8:76
      |
    8 | #![cfg_attr(feature = "const_fn", feature(const_fn, const_unsafe_cell_new, const_atomic_usize_new))]
      |                                                                            ^^^^^^^^^^^^^^^^^^^^^^
    
    error[E0635]: unknown feature `const_unsafe_cell_new`
     --> /home/amram/.cargo/registry/src/github.com-1ecc6299db9ec823/spin-0.4.8/src/lib.rs:8:53
      |
    8 | #![cfg_attr(feature = "const_fn", feature(const_fn, const_unsafe_cell_new, const_atomic_usize_new))]
      |                                                     ^^^^^^^^^^^^^^^^^^^^^
    
    error: aborting due to 2 previous errors
    
    For more information about this error, try `rustc --explain E0635`.
    error: Could not compile `spin`.
    
    Caused by:
      process didn't exit successfully: `rustc --crate-name spin /home/amram/.cargo/registry/src/github.com-1ecc6299db9ec823/spin-0.4.8/src/lib.rs --crate-type lib --emit=dep-info,link -C opt-level=3 --cfg 'feature="asm"' --cfg 'feature="const_fn"' --cfg 'feature="core_intrinsics"' --cfg 'feature="default"' --cfg 'feature="once"' --cfg 'feature="unstable"' -C metadata=6da928f3fd28acf3 -C extra-filename=-6da928f3fd28acf3 --out-dir /tmp/pip-install-xv02w1v3/autopy/target/release/deps -L dependency=/tmp/pip-install-xv02w1v3/autopy/target/release/deps --cap-lints allow` (exit code: 1)
    warning: build failed, waiting for other jobs to finish...
    error: build failed
    error: cargo failed with code: 101
    
    
    ----------------------------------------
Command "/usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-xv02w1v3/autopy/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-3ofcoj9a/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-install-xv02w1v3/autopy/

> 

Could you help me pls ?

**Comment by msanders** [comment]
Hi, sorry for the delay. Can you try again on the latest version and see if that fixes it?

**Comment by ornariece** [comment]
It works now, thanks !
