### ISSUE TITLE
Autopy in wheel format for Python 27, 36 and 37 (32 and 64 bits)

### ISSUE THREAD

**Issue by palvarezlopez** [autopilot-rs/autopy#21]
Hi Michael,

Thank you very much for this useful script, we're using it for testing the interface of our project [SUMO](https://github.com/eclipse/sumo). I prepared four six wheel packages for Python 27, 36 and 37, (Bot in 32 and 64 bits), to make it more easy to install.

https://github.com/DLR-TS/SUMOLibraries/tree/master/python/autopy

Regards

**Comment by msanders** [comment]
Thanks @palvarezlopez! This should be updated shortly on PyPI (see #18 and #19), will close this out once done. Also added a link back to SUMO from the README.
