### ISSUE TITLE
Inconsistent behavior for bitmap.capture_screen() on ArchLinux (i3-wm)

### ISSUE THREAD

**Issue by ornariece** [autopilot-rs/autopy#24]
Hi. I'm trying to get a screenshot of a region of my screen. Here is the coordinates of the region : autopy.bitmap.capture_screen(((1680, 56), (1920, 1144))).
So the region would go to (3600, 1200) on my screen, and the screenshot should be possible, since my screen size is 3600x1200. As a proof, here is the output of the xrandr command : 

>  Screen 0: minimum 320 x 200, current 3600 x 1200, maximum 8192 x 8192
HDMI-1 connected primary 1920x1200+1680+0 (normal left inverted right x axis y axis) 518mm x 324mm
VGA-1 connected 1680x1050+0+0 (normal left inverted right x axis y axis) 433mm x 271mm

So yea, the autopy method capture_screen() should work with these coordinates, but I'm getting the "Image too large or too small" error.

I was thinking there might be a 1pixel offset, so I tried autopy.bitmap.capture_screen(((1680, 56), (1919, 1143))), and even weirder, this worked a few times and didn't the other times !

I'm out of ideas, I'm quite sure I'm not doing anything wrong. I asked a friend which is also on ArchLinux with i3-wm and he has the same inconsistent behavior.

**Comment by msanders** [comment]
Hmm, not sure. It might be related to scaling (ex. 
https://github.com/autopilot-rs/autopilot-rs/blob/e59f0aa/src/internal.rs#L68). What are the values of `screen.size()` and `screen.scale()`?

**Comment by ornariece** [comment]
> >>> autopy.screen.size()
(3598.1102362204724, 1199.3700787401574)
>>> autopy.screen.scale()
1.0005252100840336

Right, I can see why it fails now, is this a float error or smth ?

**Comment by msanders** [comment]
I've pushed a potential fix, can you try again on the latest master?

**Comment by ornariece** [comment]
Yep it seems to be fixed ! Thanks.
