### ISSUE TITLE
Windows / Super key support

### ISSUE THREAD

**Issue by lyneca** [autopilot-rs/autopy#27]
I can't find any sign of support for the windows/start/super key modifier. Is the library able to generate this?

**Comment by tobegit3hub** [comment]
Got similar issue for Mac and Windows.

<img width="616" alt="screenshot 2019-03-02 at 11 06 43 am" src="https://user-images.githubusercontent.com/2715000/53676307-4e428f00-3cdb-11e9-96b2-c4fe87ec4774.png">

**Comment by msanders** [comment]
@lyneca: this should be possible with `autopy.key.tap(autopy.key.Modifier.META, [])`, I've updated the docs accordingly: https://github.com/autopilot-rs/autopy/commit/86c4488bb3d3543868352925d4ad36298ac82c97.

**Comment by msanders** [comment]
https://github.com/autopilot-rs/autopy/issues/27#issuecomment-468876832 is a duplicate of #29.
