### ISSUE TITLE
How can I use autopy.key

### ISSUE THREAD

**Issue by DTDwind** [autopilot-rs/autopy#29]
Python 3.5
linux mint

When I use "autopy.key.toggle("1",True,autopy.key.MOD_CONTROL)"
I get:
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'autopy.key' has no attribute 'MOD_CONTROL'

Then I try "autopy.key.toggle("a",True,autopy.key.Modifier.CONTROL)"
get:
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError

When I use autopy.key.tap(autopy.key.Code.RETURN)
get:
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: Required argument ('modifiers') (pos 2) not found

I don't know how to use this function...
Maybe you can give me some example,thanks!

**Comment by DTDwind** [comment]
I get it!!!

autopy.key.tap(autopy.key.Code.RETURN,[])
autopy.key.tap('a', [autopy.key.Modifier.CONTROL])

**Comment by fl0under** [comment]
I just ran into the same issue, I was expecting autopy.key.tap(autopy.key.Code.RETURN) to work but got 

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: Required argument ('modifiers') (pos 2) not found

Thanks DTDwind for posting a working example. I think the docs need some updating.

**Comment by msanders** [comment]
@DTDwind @fl0under: where did you see this shown in the docs? It looks like it does include `List[Modifier]` in the signature, but maybe it would be helpful to post an example somewhere.
