### ISSUE TITLE
mouse.click() does not do mouse up

### ISSUE THREAD

**Issue by badeendjuh** [autopilot-rs/autopy#3]
Setup:
autopy==1.0.1
python 3.6

Interacting with a VNC linux session like so:

```
autopy.mouse.move(1032, 126)
autopy.mouse.click()
```

This will move the mouse to the correct location
Then the mouse-down is issued, but a mouse-up does not occur.

If in this position I issue:

```
autopy.mouse.toggle(autopy.mouse.Button.LEFT, False)
```

The mouse up is given.

**Comment by msanders** [comment]
My guess is the [delay](https://github.com/autopilot-rs/autopilot-rs/blob/9f5e8cce66a9a7dba4619b553321407c087c064d/src/mouse.rs#L77) isn't long enough for the click to register in VNC. I'll update this in the next release to take an explicit `delay` parameter so it can be increased.

**Comment by pevogam** [comment]
I can confirm the same issue on Fedora 27 without the VNC session (physical workstation as well as a docker image). Using the `toggle(..., False)` step solves the issue for the time being.

**Comment by msanders** [comment]
This should be fixed by https://github.com/autopilot-rs/autopilot-rs/pull/8 (which is included on the latest master), I just haven't had time yet to distribute the new binary wheels.

**Comment by msanders** [comment]
This is fixed on the latest master. Moved binary wheel distribution task to separate issue: https://github.com/autopilot-rs/autopy/issues/18.
