### ISSUE TITLE
[Question] Transform autopy.bitmap.Bitmap into numpy.array?

### ISSUE THREAD

**Issue by surister** [autopilot-rs/autopy#30]
Is there any way to transform autopy.bitmap.Bitmap into numpy.array?, I've been looking it up and trying a few things and failed.

**Comment by msanders** [comment]
I've listed an entry [on the FAQ](https://github.com/autopilot-rs/autopy/wiki/FAQ#how-do-i-get-access-to-the-raw-buffer-in-an-autopy-bitmap) showing how to access the RGBA buffer as a bytes array. Is that a good enough starting point for numpy?

**Comment by surister** [comment]
Sure thing, thanks!

**Comment by msanders** [comment]
👍 I've updated the homepage to link back to this and make it easier to find. Let me know if you run into anything else.
