### ISSUE TITLE
python setup.py install permission error

### ISSUE THREAD

**Issue by plamenh** [autopilot-rs/autopy#31]
Long story short, I have to use the compile method, because on a raspbian stretch nothing else seems to work (not sure this will work either yet). At the last step I get a permission error:

```
The following error occurred while trying to add or remove files in the
installation directory:

    [Errno 13] Permission denied: '/usr/local/lib/python2.7/dist-packages/test-easy-install-1800.write-test'
```

sudo does not work, because apparently rust compiler works at the user level. Apart from repeating the whole process as root, anyone can suggest another method?

**Comment by msanders** [comment]
Hi @plamenh, can you try `python setup.py install --user`?

**Comment by plamenh** [comment]
Ultimately did the install as root and now it works.
