### ISSUE TITLE
Autopy install error

### ISSUE THREAD

**Issue by bukiyu08** [autopilot-rs/autopy#33]
Hi,

I'm trying to install autopy, but I get some errors. I have triying some stuff but nothing seems to work. Errors are below, thanks for the help.

pi@raspberrypi:~/autopy $ python setup.py build
running build
running build_py
creating build
creating build/lib.linux-armv7l-2.7
creating build/lib.linux-armv7l-2.7/autopy
copying autopy/__init__.py -> build/lib.linux-armv7l-2.7/autopy
running build_ext
running build_rust
    Updating crates.io index
  Downloaded rand_jitter v0.1.4
  Downloaded scopeguard v1.0.0
  Downloaded rand_xorshift v0.1.1
  Downloaded rand_isaac v0.1.1
  Downloaded rand_hc v0.1.0
  Downloaded rand v0.6.5
  Downloaded png v0.14.1
  Downloaded spin v0.5.0
  Downloaded rand_os v0.1.3
  Downloaded cloudabi v0.0.3
  Downloaded ghost v0.1.0
  Downloaded rand_pcg v0.1.2
  Downloaded rand_chacha v0.1.1
  Downloaded pyo3-derive-backend v0.6.0
  Downloaded pyo3cls v0.6.0
  Downloaded pyo3 v0.6.0
  Downloaded ctor v0.1.9
  Downloaded inventory v0.1.3
  Downloaded autopilot v0.2.1
  Downloaded inventory-impl v0.1.3
  Downloaded image v0.21.2
  Downloaded 21 crates (975.4 KB) in 1.62s
cargo rustc --lib --manifest-path Cargo.toml --features pyo3/extension-module pyo3/python2 --release --verbose -- --crate-type cdylib
   Compiling arrayvec v0.4.11
   Compiling lazy_static v1.3.0
   Compiling libc v0.2.60
   Compiling proc-macro2 v0.4.30
     Running `rustc --crate-name build_script_build /home/pi/.cargo/registry/src/github.com-1ecc6299db9ec823/arrayvec-0.4.11/build.rs --color always --crate-type bin --emit=dep-info,link -C opt-level=3 -C metadata=c8a43e12762695d1 -C extra-filename=-c8a43e12762695d1 --out-dir /home/pi/autopy/target/release/build/arrayvec-c8a43e12762695d1 -L dependency=/home/pi/autopy/target/release/deps --cap-lints allow`
     Running `rustc --crate-name lazy_static /home/pi/.cargo/registry/src/github.com-1ecc6299db9ec823/lazy_static-1.3.0/src/lib.rs --color always --crate-type lib --emit=dep-info,metadata,link -C opt-level=3 -C metadata=7517fd82bb3c82a3 -C extra-filename=-7517fd82bb3c82a3 --out-dir /home/pi/autopy/target/release/deps -L dependency=/home/pi/autopy/target/release/deps --cap-lints allow`
     Running `rustc --crate-name build_script_build /home/pi/.cargo/registry/src/github.com-1ecc6299db9ec823/proc-macro2-0.4.30/build.rs --color always --crate-type bin --emit=dep-info,link -C opt-level=3 --cfg 'feature="default"' --cfg 'feature="proc-macro"' -C metadata=d21b74293a25bb41 -C extra-filename=-d21b74293a25bb41 --out-dir /home/pi/autopy/target/release/build/proc-macro2-d21b74293a25bb41 -L dependency=/home/pi/autopy/target/release/deps --cap-lints allow`
     Running `rustc --crate-name build_script_build /home/pi/.cargo/registry/src/github.com-1ecc6299db9ec823/libc-0.2.60/build.rs --color always --crate-type bin --emit=dep-info,link -C opt-level=3 --cfg 'feature="default"' --cfg 'feature="std"' -C metadata=2e454f5878c8d297 -C extra-filename=-2e454f5878c8d297 --out-dir /home/pi/autopy/target/release/build/libc-2e454f5878c8d297 -L dependency=/home/pi/autopy/target/release/deps --cap-lints allow`
error: Could not compile `lazy_static`.

Caused by:
  process didn't exit successfully: `rustc --crate-name lazy_static /home/pi/.cargo/registry/src/github.com-1ecc6299db9ec823/lazy_static-1.3.0/src/lib.rs --color always --crate-type lib --emit=dep-info,metadata,link -C opt-level=3 -C metadata=7517fd82bb3c82a3 -C extra-filename=-7517fd82bb3c82a3 --out-dir /home/pi/autopy/target/release/deps -L dependency=/home/pi/autopy/target/release/deps --cap-lints allow` (signal: 11, SIGSEGV: invalid memory reference)
warning: build failed, waiting for other jobs to finish...
thread '<unnamed>' panicked at 'index out of bounds: the len is 0 but the index is 4294967280', /rustc/e649e903440bfd919bfc9db848c28df6d795a116/src/libcore/slice/mod.rs:2681:10
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
thread '<unnamed>' panicked at 'src/librustc_codegen_ssa/back/write.rs:1545: worker thread panicked', src/librustc/util/bug.rs:37:26
munmap_chunk(): invalid pointer
error: Could not compile `arrayvec`.

Caused by:
  process didn't exit successfully: `rustc --crate-name build_script_build /home/pi/.cargo/registry/src/github.com-1ecc6299db9ec823/arrayvec-0.4.11/build.rs --color always --crate-type bin --emit=dep-info,link -C opt-level=3 -C metadata=c8a43e12762695d1 -C extra-filename=-c8a43e12762695d1 --out-dir /home/pi/autopy/target/release/build/arrayvec-c8a43e12762695d1 -L dependency=/home/pi/autopy/target/release/deps --cap-lints allow` (signal: 6, SIGABRT: process abort signal)
warning: build failed, waiting for other jobs to finish...
error: Could not compile `libc`.

Caused by:
  process didn't exit successfully: `rustc --crate-name build_script_build /home/pi/.cargo/registry/src/github.com-1ecc6299db9ec823/libc-0.2.60/build.rs --color always --crate-type bin --emit=dep-info,link -C opt-level=3 --cfg 'feature="default"' --cfg 'feature="std"' -C metadata=2e454f5878c8d297 -C extra-filename=-2e454f5878c8d297 --out-dir /home/pi/autopy/target/release/build/libc-2e454f5878c8d297 -L dependency=/home/pi/autopy/target/release/deps --cap-lints allow` (signal: 11, SIGSEGV: invalid memory reference)
warning: build failed, waiting for other jobs to finish...
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: Utf8Error { valid_up_to: 6, error_len: Some(1) }', src/libcore/result.rs:1051:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
thread '<unnamed>' panicked at 'src/librustc_codegen_ssa/back/write.rs:1545: worker thread panicked', src/librustc/util/bug.rs:37:26
error: Could not compile `proc-macro2`.

Caused by:
  process didn't exit successfully: `rustc --crate-name build_script_build /home/pi/.cargo/registry/src/github.com-1ecc6299db9ec823/proc-macro2-0.4.30/build.rs --color always --crate-type bin --emit=dep-info,link -C opt-level=3 --cfg 'feature="default"' --cfg 'feature="proc-macro"' -C metadata=d21b74293a25bb41 -C extra-filename=-d21b74293a25bb41 --out-dir /home/pi/autopy/target/release/build/proc-macro2-d21b74293a25bb41 -L dependency=/home/pi/autopy/target/release/deps --cap-lints allow` (signal: 11, SIGSEGV: invalid memory reference)
error: cargo failed with code: 101

**Comment by bukiyu08** [comment]
I solved this by using "autopy3" instead. Not sure why autopy didn't work tho.

**Comment by msanders** [comment]
@bukiyu08 Sorry for the delay, just seeing this now. What platform are you running this on? `autopy3` is actually a legacy version of AutoPy that should no longer be used. Python 3 is fully supported by this version.
