### ISSUE TITLE
mistake in example `autopy.color.hex_to_rgb(autopy.screen.get_color(1, 1))` 

### ISSUE THREAD

**Issue by furas** [autopilot-rs/autopy#34]
Your example on [main page](https://github.com/autopilot-rs/autopy)

```
>>> import autopy
>>> autopy.color.hex_to_rgb(autopy.screen.get_color(1, 1))
(242, 242, 242)
```

gives error 

`TypeError: 'tuple' object cannot be interpreted as an integer`

To get `RGB` tuple it doesn't need `hex_to_rgb()`

```
>>> import autopy
>>> autopy.screen.get_color(1, 1)
(242, 242, 242)
```

You can only use `rgb_to_hex` instead of `hex_to_rgb` to get hex value

```
>>> import autopy
>>> autopy.color.rgb_to_hex(*autopy.screen.get_color(1, 1))
15921906
```

Tested on: Linux Mint 19.2 / Python 3.7.4 / autopy 2.1.0

There was question on Stackoverflow for this: [Why does this line of code produce the TypeError: 'tuple' object cannot be interpreted as an integer](https://stackoverflow.com/questions/57628471/why-does-this-line-of-code-produce-the-typeerror-tuple-object-cannot-be-inter)

**Comment by msanders** [comment]
Thanks for pointing this out. It looks like this was changed to make it consistent with the Rust layer. I've changed it instead to revert to the previous behavior as that should be more efficient in Python, so this line should work as-is with the next major release.
