### ISSUE TITLE
Can't toggle modifier keys

### ISSUE THREAD

**Issue by cool-RR** [autopilot-rs/autopy#39]
I've been trying to toggle the modifier keys, but I guess I'm doing something wrong:
```
>>> autopy.key.toggle(autopy.key.Modifier.ALT, False, [])
TypeError: Expected string or key code
```

How should this be done?

**Comment by msanders** [comment]
It should be: `autopy.key.toggle("x", False, [autopy.key.Modifier.ALT])`.

**Comment by msanders** [comment]
This looks like a dupe of #29, will have to add an example to the docs somewhere.

**Comment by cool-RR** [comment]
@msanders Where's the `"x"` coming from? I want toggle just the modifier key, nothing else.

**Comment by msanders** [comment]
Have you tried `autopy.key.toggle("", False, [autopy.key.Modifier.ALT])`? I think that should work but don't have time to test it out right now.

**Comment by cool-RR** [comment]
Nope:
```
TypeError: Expected string or key code
```

**Comment by msanders** [comment]
Ah I see. It looks like we need to add those as individual key codes, e.g. https://github.com/servo/core-foundation-rs/blob/8793a46/core-graphics/src/event.rs#L53.

**Comment by msanders** [comment]
Actually it looks like this is already available, just missing from the docs:

```python
autopy.key.tap(autopy.key.Code.META, [])
```

**Comment by cool-RR** [comment]
Well, that sends the key, doesn't it? What I want is to toggle off the modifiers, in case they were pressed.

**Comment by msanders** [comment]
This should work: `autopy.key.toggle(autopy.key.Code.META, False, [])`, was just pointing out the key code.

**Comment by cool-RR** [comment]
Okay, that works. Should be included in the docs, right?

**Comment by msanders** [comment]
👍 yup, should be included now.
