### ISSUE TITLE
mouse.location() coordinates do not equal mouse.move() coordinates

### ISSUE THREAD

**Issue by Dr-Chronosphere** [autopilot-rs/autopy#42]
I used the mouse.location() method to figure out where I needed to automate moving the cursor, but when I plugged the values into mouse.move(), it always threw a ValueError exception due to it being "out of bounds." Long story short, I used code to figure out that the mouse.location() coordinate system is exactly 25% greater than the system mouse.move uses. This seems to be a rather large oversight. If the coordinate systems are for some reason not meant to be equal, please update the documentation to mention this decision. Thanks.

**Comment by msanders** [comment]
Thanks for the report. Can you add which platform this was on so I can try reproducing? And also the value of `screen.scale()`.

**Comment by msanders** [comment]
This is now fixed upstream by https://github.com/autopilot-rs/autopilot-rs/commit/2bc5bb140923b2711e29b78bc5300a01407d3970, will be deploying a new release shortly.

**Comment by msanders** [comment]
Included in version 3.0.1.
