### ISSUE TITLE
 Relicense under dual MIT-or-Apache-2.0

### ISSUE THREAD

**Issue by msanders** [autopilot-rs/autopy#44]
I'd like to relicense this project from Apache 2.0 to an MIT-or-Apache dual license for consistency with the Rust community, and to allow GPLv2 compatibility, which I was previously unaware was disallowed by Apache.

For more information, see the issue here: https://github.com/autopilot-rs/autopilot-rs/issues/26.

To do this, it’s necessary to get explicit approval from each contributor (aside from small typo fixes, etc., as described in the above links)

- [x] @msanders
- [x] @svanellewee

@svanellewee, you've been the only other contributor to this repo thus far, would you mind signing off by commenting here with the following?

> I license past and future contributions under the dual MIT-or-Apache-2.0 license, allowing licensees to choose either at their option.

Then I'll be able to make the change right away. Thanks for your help!

**Comment by msanders** [comment]
I license past and future contributions under the dual MIT-or-Apache-2.0 license, allowing licensees to choose either at their option.

**Comment by msanders** [comment]
@svanellewee just saw your message in the other thread, thank you! Would you mind confirming that is meant for this repo (`autopilot-rs/autopy`)?

**Comment by svanellewee** [comment]
I license past and future contributions under the dual MIT-or-Apache-2.0 license, allowing licensees to choose either at their option.

**Comment by svanellewee** [comment]
Oops! Sorry! And done. Was wondering why my name wasn't in the issue description ! :-P

**Comment by msanders** [comment]
Thanks Stephan!
