### ISSUE TITLE
Adding TAB to Code section

### ISSUE THREAD

**Issue by NogradThGin** [autopilot-rs/autopy#46]
Is it possible to add     
```rust
    #[getter(TAB)]
    fn tab(&self) -> PyResult<Py<Code>> {
        self.init_code_ref(autopilot::key::KeyCode::Tab)
    }
```

to the impl _Code section, tested at home it work perfectly.
Actually there is no key listed (or did I failed in my search ?) which allow to do a tab

**Comment by msanders** [comment]
Yes - please open a PR! Looks like this was a small oversight, the code you wrote above looks fine. Otherwise I'll add one shortly.
