### ISSUE TITLE
ValueError thrown when converting bitmap to PIL Image

### ISSUE THREAD

**Issue by msanders** [autopilot-rs/autopy#48]
Running the [suggested code](https://github.com/autopilot-rs/autopy/wiki/FAQ#how-do-i-get-access-to-the-raw-buffer-in-an-autopy-bitmap) on the FAQ now produces this error:

```
>>> import autopy
>>> import PIL.Image
>>> bmp = autopy.bitmap.capture_screen()
>>> width, height = int(round(bmp.width * bmp.scale)), int(round(bmp.height * bmp.scale))
>>> img = PIL.Image.frombytes('RGBA', (width, height), bytes(bmp))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/mks/.pyenv/versions/3.8.0/Python.framework/Versions/3.8/lib/python3.8/site-packages/PIL/Image.py", line 2581, in frombytes
    im.frombytes(data, decoder_name, args)
  File "/Users/mks/.pyenv/versions/3.8.0/Python.framework/Versions/3.8/lib/python3.8/site-packages/PIL/Image.py", line 772, in frombytes
    raise ValueError("not enough image data")
ValueError: not enough image data
```

See also: https://github.com/autopilot-rs/autopy/issues/47#issuecomment-570532224.

**Comment by Michal-Miko** [comment]
I have no experience with rust but it appears that the bytes function returns an RGB pixel buffer instead of RGBA. 
Reading the image from bytes with `img = PIL.Image.frombytes('RGB', (width, height), bytes(bmp))` seems to work.

**Comment by msanders** [comment]
@Michal-Miko that indeed fixes the issue, thank you! Updated the FAQ.
