### ISSUE TITLE
Keyboard and mouse control don't work on macOS Mojave

### ISSUE THREAD

**Issue by yanan-xu** [autopilot-rs/autopy#53]
I used the sine_mouse_wave as my example, but it doesn't works. 
And no error messges.

**Comment by msanders** [comment]
Thanks for the report. Have you checked accessibility settings? See System Preferences > Security & Privacy > Privacy > Accessibility and confirm Terminal is checked.

**Comment by yanan-xu** [comment]
@msanders  Thank you, it's the problem.
