### ISSUE TITLE
string shortcuts with MODIFIERS don't work

### ISSUE THREAD

**Issue by ProsperChuks** [autopilot-rs/autopy#66]
autopy.key.tap("S", [autopy.key.Modifier.CONTROL]

- this returns the string back, it doesn't Ctrl + S

**Comment by meflakcannon** [comment]
You might want to try the following instead.

```
def event_ctrl_s():
    autopy.key.tap(u'S', autopy.key.CONTROL)
```

**Comment by ProsperChuks** [comment]
> You might want to try the following instead.
> 
> ```
> def event_ctrl_s():
>     autopy.key.tap(u'S', autopy.key.CONTROL)
> ```

Thanks.
