### ISSUE TITLE
Right click

### ISSUE THREAD

**Issue by bhuvanjs25** [autopilot-rs/autopy#73]
autopy.mouse.Button:RIGHT 
does not work
How Can i use Right click of mouse. please help

**Comment by meflakcannon** [comment]
`
def event_right_click():
  autopy.mouse.click(autopy.mouse.RIGHT_BUTTON)
`

**Comment by bhuvanjs25** [comment]
Traceback (most recent call last):
  File "C:/Users/bhuva/PycharmProjects/mouse/AiVirtualMouseProject.py", line 69, in <module>
    autopy.mouse.click(autopy.mouse.RIGHT_BUTTON)
AttributeError: module 'autopy.mouse' has no attribute 'RIGHT_BUTTON'
[ WARN:0] global C:\Users\runneradmin\AppData\Local\Temp\pip-req-build-inblc7p7\opencv\modules\videoio\src\cap_msmf.cpp (438) `anonymous-namespace'::SourceReaderCB::~SourceReaderCB terminating async callback

Tried every thing it is right click function is not in autopy looks like

**Comment by meflakcannon** [comment]
Care to share your code so we can see how you are implementing click? The above code worked without issue for me.

**Comment by meflakcannon** [comment]
If you are dead set on using this autopy tool. Which is just a rust wrapper. I'd say look at the actual source to better understand.

However alternativly use the following module.

```
import pyautogui
def event_rightclick():
    pyautogui.click(button='right')
    time.sleep(1)
```

**Comment by bhuvanjs25** [comment]
# 8. Both Index and middle fingers are up : Clicking Mode
if fingers[1] == 1 and fingers[2] == 1:
    # 9. Find distance between fingers
    length, img, lineInfo = detector.findDistance(8, 12, img)
    print(length)
# 10. Click mouse if distance short
    if length < 40:
        cv2.circle(img, (lineInfo[4], lineInfo[5]),
               15, (0, 255, 0), cv2.FILLED)
        #def event_right_click():
        autopy.mouse.click(autopy.mouse.RIGHT_BUTTON)

i think should be enough

**Comment by meflakcannon** [comment]
your using a different version of autopy than I. I think the process was autopy.mouse.click(autopy.mouse.RIGHT), but I've moved off this tool since it's a rust wrapper, and not maintained or updated well. pyautogui achieves the same thing with python native code.

**Comment by bhuvanjs25** [comment]
C:\Users\bhuva>pip install -V autopy
Requirement already satisfied: autopy in
c:\users\bhuva\appdata\local\programs\python\python37\lib\site-packages
(4.0.0)
i think i have to include pyautogui
can i use both in one program

**Comment by meflakcannon** [comment]
You can use pyautogui and yes your autopy version reads as 4.0 I'm specifically using autopy3 which had RIGHT_BUTTON and it looks like it's since changed. Regardless I'd recommend doing pyautogui everywhere. Simply because anyone you share this code with will need to install packages which is easier with supported non abandoned codebases.

**Comment by bhuvanjs25** [comment]
Thanks for the tip!
I will Definitely do it

**Comment by bhuvanjs25** [comment]
Close
